#ddev-generated
# If you remove the ddev-generated line above you
# are responsible for maintaining this file. DDEV will not then
# update it, for example if you add `additional_hostnames`, etc.

http:
  routers:
    temp-xhgui-80-http:
      entrypoints:
        - http-8143
      rule: HostRegexp(`^temp\.ddev\.site$`)
      
      service: "temp-xhgui-80"
      tls: false
      # middlewares:
      #   - "temp-redirectHttps"
    temp-web-80-http:
      entrypoints:
        - http-80
      rule: HostRegexp(`^temp\.ddev\.site$`)
      
      service: "temp-web-80"
      tls: false
      # middlewares:
      #   - "temp-redirectHttps"
    temp-web-8025-http:
      entrypoints:
        - http-8025
      rule: HostRegexp(`^temp\.ddev\.site$`)
      
      service: "temp-web-8025"
      tls: false
      # middlewares:
      #   - "temp-redirectHttps"
    temp-web-3000-http:
      entrypoints:
        - http-3001
      rule: HostRegexp(`^temp\.ddev\.site$`)
      
      service: "temp-web-3000"
      tls: false
      # middlewares:
      #   - "temp-redirectHttps"
    
    
    temp-xhgui-80-https:
      entrypoints:
        - http-8142
      rule: HostRegexp(`^temp\.ddev\.site$`)
      
      service: "temp-xhgui-80"
      
      tls: true
      
    
    
    
    temp-web-80-https:
      entrypoints:
        - http-443
      rule: HostRegexp(`^temp\.ddev\.site$`)
      
      service: "temp-web-80"
      
      tls: true
      
    temp-web-8025-https:
      entrypoints:
        - http-8026
      rule: HostRegexp(`^temp\.ddev\.site$`)
      
      service: "temp-web-8025"
      
      tls: true
      
    temp-web-3000-https:
      entrypoints:
        - http-3000
      rule: HostRegexp(`^temp\.ddev\.site$`)
      
      service: "temp-web-3000"
      
      tls: true
      
    

  middlewares:
    temp-redirectHttps:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    temp-xhgui-80:
      loadbalancer:
        servers:
          - url: http://ddev-temp-xhgui:80
        
    
    temp-web-80:
      loadbalancer:
        servers:
          - url: http://ddev-temp-web:80
        
    temp-web-8025:
      loadbalancer:
        servers:
          - url: http://ddev-temp-web:8025
        
    temp-web-3000:
      loadbalancer:
        servers:
          - url: http://ddev-temp-web:3000
        
    
    
    
    

tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/temp.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/temp.key