#ddev-generated
# If you remove the ddev-generated line above you
# are responsible for maintaining this file. DDEV will not then
# update it, for example if you add `additional_hostnames`, etc.

http:
  routers:
    test-web-80-http:
      entrypoints:
        - http-80
      rule: HostRegexp(`^test\.ddev\.site$`)
      
      service: "test-web-80"
      tls: false
      # middlewares:
      #   - "test-redirectHttps"
    test-web-8025-http:
      entrypoints:
        - http-8025
      rule: HostRegexp(`^test\.ddev\.site$`)
      
      service: "test-web-8025"
      tls: false
      # middlewares:
      #   - "test-redirectHttps"
    test-web-3000-http:
      entrypoints:
        - http-3001
      rule: HostRegexp(`^test\.ddev\.site$`)
      
      service: "test-web-3000"
      tls: false
      # middlewares:
      #   - "test-redirectHttps"
    test-xhgui-80-http:
      entrypoints:
        - http-8143
      rule: HostRegexp(`^test\.ddev\.site$`)
      
      service: "test-xhgui-80"
      tls: false
      # middlewares:
      #   - "test-redirectHttps"
    
    
    
    
    test-web-80-https:
      entrypoints:
        - http-443
      rule: HostRegexp(`^test\.ddev\.site$`)
      
      service: "test-web-80"
      
      tls: true
      
    test-web-8025-https:
      entrypoints:
        - http-8026
      rule: HostRegexp(`^test\.ddev\.site$`)
      
      service: "test-web-8025"
      
      tls: true
      
    test-web-3000-https:
      entrypoints:
        - http-3000
      rule: HostRegexp(`^test\.ddev\.site$`)
      
      service: "test-web-3000"
      
      tls: true
      
    
    test-xhgui-80-https:
      entrypoints:
        - http-8142
      rule: HostRegexp(`^test\.ddev\.site$`)
      
      service: "test-xhgui-80"
      
      tls: true
      
    

  middlewares:
    test-redirectHttps:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    test-web-80:
      loadbalancer:
        servers:
          - url: http://ddev-test-web:80
        
    test-web-8025:
      loadbalancer:
        servers:
          - url: http://ddev-test-web:8025
        
    test-web-3000:
      loadbalancer:
        servers:
          - url: http://ddev-test-web:3000
        
    
    
    
    test-xhgui-80:
      loadbalancer:
        servers:
          - url: http://ddev-test-xhgui:80
        
    
    

tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/test.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/test.key