dateModified: 1776072996
email:
  fromEmail: $SYSTEM_EMAIL
  fromName: $SYSTEM_SENDER_NAME
  replyToEmail: $SYSTEM_EMAIL_REPLY_TO
  template: ''
  transportSettings:
    token: $POSTMARK_TOKEN
  transportType: craftcms\postmark\Adapter
meta:
  __names__:
    3cc4acf3-605a-484d-bdec-eaad0e0bdbad: tes # tes
    3ced4412-76be-4b8f-b07c-8a30af47ff32: New # New
    99529fbf-4d35-4f2c-a3a5-8bf20e08045f: tes # tes
    407957b4-deb8-4791-b4c5-306c8198f788: 'Contact Form' # Contact Form
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 5.0.0.1
  cp-clearcache:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  formie:
    edition: standard
    enabled: true
    licenseKey: 6I5TBQWW8WO62HN4VJ6F2OXK
    schemaVersion: 3.4.12
  logging-library:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  postmark:
    edition: standard
    enabled: true
    schemaVersion: 2.0.1
  redirect-manager:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  seomatic:
    edition: standard
    enabled: true
    licenseKey: F57O6XORBT9YIQMOYV7D8OS6
    schemaVersion: 3.0.13
  servd-asset-storage:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: $SYSTEM_STATUS
  name: tes
  schemaVersion: 5.9.0.8
  timeZone: $SYSTEM_TIMEZONE
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
