name: test
type: craftcms
docroot: web
php_version: "8.3"
webserver_type: nginx-fpm
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
    type: mysql
    version: "8.0"
webimage_extra_packages: [build-essential, libvips-dev]
use_dns_when_possible: true
timezone: Europe/Berlin
composer_version: "2"
nodejs_version: "22"
corepack_enable: false
web_environment:
    - CPPFLAGS=-DPNG_ARM_NEON_OPT=0
upload_dirs:
    - web/assets
    - storage
